import { parseNaturalLanguage } from './ai.service.js';
import { resolveDestination } from './destination.service.js';
import { detectMissingTripInformation } from './missingInfo.service.js';
const words={one:1,two:2,three:3,four:4,five:5,six:6,seven:7,eight:8,nine:9,ten:10};
const title=value=>value.toLowerCase().replace(/\b\w/g,c=>c.toUpperCase());
const normalizeInterests=text=>{const out=[],add=(r,...values)=>r.test(text)&&values.forEach(v=>!out.includes(v)&&out.push(v));add(/temple|spiritual/i,'Temple');add(/mahal|palace/i,'Palace','Heritage','Architecture');add(/old building|heritage/i,'Heritage','Architecture');add(/jigarthanda|traditional food|street food/i,'Traditional Food');add(/beach/i,'Beach');add(/photo|instagram/i,'Photography');add(/food|cafe/i,'Food');add(/nature|park|waterfall|hill/i,'Nature');add(/shop|market/i,'Shopping');return out};
const numberValue=value=>/^\d+$/.test(value)?Number(value):words[value.toLowerCase()]||null;
export function fallbackTripRequest(text=''){
 const durationMatch=text.match(/\b(\d+|one|two|three|four|five|six|seven|eight|nine|ten)\s*[- ]?days?\b/i),durationDays=durationMatch?numberValue(durationMatch[1]):null,people=text.match(/\b(\d+|one|two|three|four|five|six|seven|eight|nine|ten)\s*(?:friends|people|travell?ers?|persons?)\b/i);
 const explicitBudget=text.match(/(?:₹|rs\.?|inr|budget(?:\s+(?:of|is))?|under)\s*([\d,]+)|([\d,]+)\s*(?:rupees?|inr|budget)\b/i),durationDigits=new Set(durationMatch?.[0].match(/\d+/g)||[]),peopleDigits=new Set(people?.[0].match(/\d+/g)||[]),bareNumbers=[...text.matchAll(/\b\d[\d,]*\b/g)].map(x=>x[0]).filter(x=>!durationDigits.has(x)&&!peopleDigits.has(x)),amount=explicitBudget?.[1]||explicitBudget?.[2]||bareNumbers.find(x=>Number(x.replaceAll(',',''))>=100);
 const pattern=/(?:plan\s+for|trip\s+to|going\s+to|going|visit(?:ing)?|want\s+to\s+go\s+to|planning\s+for|to)\s+([a-z][a-z .'-]*?)(?=\s+(?:for\s+)?(?:\d+|one|two|three|four|five|six|seven|eight|nine|ten)\s*(?:days?|₹|rs\.?|inr|budget|rupees?)|\s+with\s+\d|[,.]|$)/i;
 let candidate=text.match(pattern)?.[1]?.trim()||'';if(!candidate)candidate=text.toLowerCase().replace(/₹?\s*\d[\d,]*/g,' ').replace(/\b(?:one|two|three|four|five|six|seven|eight|nine|ten)\s*days?\b/g,' ').replace(/\b(?:days?|day|plan|trip|budget|rupees?|inr|rs|have|i|am|for|with|want|to|go|going|visit|visiting|planning|temples?|spiritual|mahal|palace|heritage|traditional|food|beach|photography|nature|shopping|tomorrow)\b/g,' ').replace(/[^a-z .'-]/g,' ').replace(/\s+/g,' ').trim();
 const avoid=[];if(/(?:avoid|no|don'?t (?:want|like))\s+museums?/i.test(text))avoid.push('Museum');if(/(?:avoid|no|don'?t (?:want|like))\s+temples?/i.test(text))avoid.push('Temple');if(/avoid crowd|no crowded|less crowded/i.test(text))avoid.push('Crowded');
 return{destination:candidate?title(candidate):null,durationDays,budget:amount?Number(amount.replaceAll(',','')):null,travellers:people?numberValue(people[1]):null,startDate:null,interests:normalizeInterests(text),avoid,originalPreferences:text,source:'deterministic'};
}
export async function parseTripRequest(text='',options={}){
 const gemini=await (options.geminiParser||parseNaturalLanguage)(text),fallback=fallbackTripRequest(text),merged={...fallback,destination:gemini.destination||fallback.destination,durationDays:gemini.durationDays??fallback.durationDays,budget:gemini.budget??fallback.budget,travellers:gemini.travellers??gemini.travelers??fallback.travellers,interests:gemini.interests?.length?gemini.interests:fallback.interests,avoid:gemini.avoid?.length?gemini.avoid:fallback.avoid};let resolvedDestination=null;
 if(merged.destination)try{resolvedDestination=await (options.destinationResolver||resolveDestination)(merged.destination);merged.destination=resolvedDestination.name||merged.destination;merged.destinationDetails=resolvedDestination}catch(error){merged.destinationResolutionError=error.status===404?'not-found':'unavailable';if(error.status===404)merged.destination=null}
 const result={...merged,missingFields:detectMissingTripInformation(merged)};if(process.env.NODE_ENV==='development')console.debug('TRIP PARSER',{rawInput:text,geminiResult:gemini,fallbackResult:fallback,destinationCandidate:fallback.destination,resolvedDestination,finalParsedTrip:result,missingFields:result.missingFields});return result;
}
