'use client';
import { useEffect, useState } from 'react';

type View='home'|'understand'|'loading'|'trip'|'active'|'recovery';
type EventType='Weather changed'|'Running late'|'Budget changed'|'Place unavailable'|null;
const prompt="We are 4 college friends visiting Chennai for one day with ₹4000. We love beaches, food and photography and don't want museums.";
const initial=[
 ['09:00','Ratna Cafe','Breakfast · Local food','₹180','92','✓'],
 ['10:20','Semmozhi Poonga','Nature · Photography','Free','88','2'],
 ['12:30','Mylapore Food Walk','Food · Culture','₹650','91','3'],
 ['15:00','Express Avenue','Shopping · Indoor','₹700','72','4'],
 ['17:15','Marina Beach','Beach · Photography','Free','94','5']
];
const adapted=[
 initial[0],
 ['12:20','Mylapore Food Walk','Food · Culture','₹650','91','2'],
 ['15:10','San Thome Basilica','Architecture · Indoor','Free','86','3'],
 ['17:30','Marina Beach','Beach · Photography','Free','94','4']
];
function Logo(){return <div className="logo"><i>↗</i>TravelMind</div>}
function Button({children,onClick,ghost=false}:{children:React.ReactNode,onClick?:()=>void,ghost?:boolean}){return <button className={'primary '+(ghost?'ghost':'')} onClick={onClick}>{children}</button>}
function Header({plan}:{plan:()=>void}){return <header><Logo/><nav><a href="#how">How it works</a><a href="#why">Intelligence</a><a href="#demo">Live demo</a></nav><div className="head-actions"><span className="avatar">AK</span><Button onClick={plan}>Plan a trip ↗</Button></div></header>}
function Home({go}:{go:()=>void}){
 const [text,setText]=useState('');
 return <main className="home"><Header plan={()=>document.querySelector('#planner')?.scrollIntoView({behavior:'smooth'})}/>
 <section className="hero"><div className="hero-copy"><div className="kicker"><i/> AI-POWERED ADAPTIVE TRAVEL</div><h1>Your trip.<br/><em>Smarter at every turn.</em></h1><p>TravelMind builds a personalized itinerary—and intelligently repairs the rest of your day when weather, delays, budgets, or availability change.</p><div className="actions"><Button onClick={()=>{setText(prompt);document.querySelector('#planner')?.scrollIntoView({behavior:'smooth'})}}>Plan my trip ↗</Button><Button ghost onClick={go}>▶ See it adapt</Button></div><div className="proof"><span className="people">AK</span><span className="people">SK</span><span className="people">PM</span><div><b>4.9 ★★★★★</b><small>Loved by smart travelers</small></div></div></div>
 <div className="visual" id="demo"><div className="halo"/><div className="mock"><div className="mock-title"><div><small>YOUR DAY IN</small><h3>Chennai adventure</h3></div><strong>92<small>score</small></strong></div><div className="route-dots"><b>1</b><i/><b>2</b><i/><b>3</b><i/><b>4</b></div>{[['09:00','Ratna Cafe','Breakfast · ₹180'],['11:00','Semmozhi Poonga','Nature · Photography'],['13:00','Mylapore Food Walk','Local food · ₹650'],['16:00','Marina Beach','Sunset · Free']].map((s,i)=><article className={i===1?'current':''} key={s[1]}><time>{s[0]}</time><span>{i+1}</span><div><b>{s[1]}</b><small>{s[2]}</small></div>{i===0&&<em>✓</em>}</article>)}</div><div className="alert"><span>☂</span><div><small>CHANGE DETECTED</small><b>Rain starts at 3:00 PM</b><p>Adapting your afternoon…</p></div><i/></div><div className="adapt"><span>✓</span><div><small>PLAN ADAPTED</small><b>Marina Beach moved</b><p>4:00 PM → 5:30 PM</p></div></div></div></section>
 <section className="planner" id="planner"><div className="kicker">PLAN WITH NATURAL LANGUAGE</div><h2>Tell us what your perfect day feels like.</h2><div className="composer"><textarea value={text} onChange={e=>setText(e.target.value)} placeholder="Tell TravelMind your destination, budget, time and what you enjoy…"/><button onClick={go}>↗</button><small>✦ AI understands the details</small></div><div className="suggestions">{['Chennai · 1 Day · ₹4,000 · Friends','Madurai · Weekend · Family · Temples + Food','Bengaluru · ₹3,000 · Cafes + Photography'].map((x,i)=><button key={x} onClick={()=>setText(i?x:prompt)}>{x}</button>)}</div></section>
 <section className="how" id="how"><div className="kicker">HOW TRAVELMIND THINKS</div><h2>One intelligent loop.<br/>A trip that stays on track.</h2><div className="steps">{[['⌁','01','UNDERSTAND','Tell us your trip naturally.'],['⌘','02','OPTIMIZE','Balance time, cost and distance.'],['↻','03','ADAPT','Repair plans when reality changes.'],['✦','04','EXPLAIN','See what changed—and why.']].map(x=><article key={x[1]}><i>{x[0]}</i><small>{x[1]}</small><h3>{x[2]}</h3><p>{x[3]}</p></article>)}</div></section>
 <section className="features" id="why"><div><div className="kicker">THE DIFFERENCE</div><h2>Built for the trip<br/>you actually take.</h2><p>Most planners stop after generating an itinerary. TravelMind keeps thinking, optimizing, and adapting throughout your day.</p></div><div className="feature-grid">{[['◎','Personalized AI','Your interests, budget and pace—not a generic list.'],['⌁','Constraint optimization','Opening hours, travel time, and cost checked before every decision.'],['↻','Adaptive recovery','Only the affected part changes. High-value moments stay protected.'],['✦','Explainable decisions','Every recommendation and change comes with a clear reason.']].map(x=><article key={x[1]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section><footer><Logo/><span>PLAN → OPTIMIZE → ADAPT → EXPLAIN</span><small>© 2026 TravelMind</small></footer></main>
}
function Top({back}:{back?:()=>void}){return <div className="top">{back&&<button onClick={back}>← Back</button>}<Logo/><span>● DEMO MODE</span></div>}
function Understand({next,back}:{next:()=>void,back:()=>void}){return <main className="flow"><Top back={back}/><section className="understand"><div className="orb">✦</div><div className="kicker">TRAVELMIND UNDERSTANDING</div><h1>Here’s what I understood.</h1><p>I turned your request into the travel requirements below. You can adjust anything before I optimize your day.</p><div className="facts">{[['⌖','DESTINATION','Chennai'],['♟','TRAVELERS','4 Friends'],['₹','TOTAL BUDGET','₹4,000'],['◷','DURATION','1 Day']].map(x=><article key={x[1]}><i>{x[0]}</i><div><small>{x[1]}</small><b>{x[2]}</b></div><button>✎</button></article>)}</div><div className="prefs"><small>INTERESTS</small><p><span>≈ Beach ×</span><span>♨ Food ×</span><span>◉ Photography ×</span><button>＋ Add</button></p><small>AVOID</small><p className="avoid"><span>⊘ Museums ×</span></p><div><label><small>TRAVEL STYLE</small><b>Friends</b></label><label><small>PACE</small><b>Moderate</b></label><label><small>TIME WINDOW</small><b>9:00 AM – 8:00 PM</b></label></div></div><aside className="ai-note">✦ <span><b>I’ll optimize for what matters to you.</b><small>Budget, opening hours, travel time, distance, and your preferences will all shape the route.</small></span></aside><Button onClick={next}>Build my smart itinerary ↗</Button><small className="powered">Powered by generative AI + constraint optimization</small></section></main>}
function Loading({done}:{done:()=>void}){const [n,setN]=useState(0);useEffect(()=>{const a=[1,2,3,4,5].map((x,i)=>setTimeout(()=>setN(x),400+i*550));const z=setTimeout(done,3300);return()=>{a.forEach(clearTimeout);clearTimeout(z)}},[done]);return <main className="loading"><Logo/><section><div className="loader"><span>✦</span></div><div className="kicker">AI + ALGORITHMS AT WORK</div><h1>Building a day that fits you.</h1><p>Balancing 25+ places against your time, budget, interests, and travel distance.</p><div className="progress">{['Understanding your preferences','Finding places you’ll love','Checking budget & opening hours','Optimizing the smartest route','Writing your personal plan'].map((x,i)=><div className={i<n?'done':i===n?'working':''} key={x}><span>{i<n?'✓':i===n?'●':'○'}</span><b>{x}</b>{i===n&&<small>working…</small>}</div>)}</div></section></main>}
function Timeline({changed}:{changed:boolean}){const data=changed?adapted:initial;return <section className="timeline"><div className="panel-head"><div><small>YOUR ITINERARY</small><h2>Tuesday, 28 August</h2></div><button>•••</button></div>{data.map((x,i)=><article className={i===0?'done':i===1?'next':''} key={x[1]}><time>{x[0]}</time><i>{i===0?'✓':i+1}</i><div className="place"><span className="photo">{['☕','✿','♨','◆','≈'][i]}</span><div><small>{x[2]}</small><em>{x[4]}% match</em><h3>{x[1]}</h3><p>★ 4.{i+4} · {x[3]} · 1h 15m</p><button>✦ Why this place?</button></div></div>{i<data.length-1&&<label>↓ &nbsp; {12+i*3} min drive</label>}</article>)}</section>}
function Map({changed}:{changed:boolean}){return <section className="map"><div className="map-head"><div><small>OPTIMIZED ROUTE</small><b>Chennai, Tamil Nadu</b></div><button>⌖ Recenter</button></div><div className="map-body"><div className="sea">BAY OF BENGAL</div><div className="route"/>{Array.from({length:changed?4:5},(_,i)=><button className={'pin p'+(i+1)+(i===1?' active':'')} key={i}>{i+1}</button>)}<label className="ml1">Ratna Cafe</label><label className="ml2">Mylapore</label><label className="ml3">Marina Beach</label><small className="credit">© OpenStreetMap</small></div></section>}
function Intel({changed}:{changed:boolean}){return <aside className="intel"><div className="intel-title">✦ <span><small>TRIP INTELLIGENCE</small><b>Your plan at a glance</b></span></div><div className="score"><strong>{changed?90:92}</strong><small>/100</small><b>GREAT MATCH</b><p>Tailored to your interests</p></div><div className="metrics">{[['₹','EST. SPEND',changed?'₹1,780':'₹2,850','of ₹4,000'],['◷','TRAVEL TIME',changed?'58m':'1h 22m','Across the day'],['⌁','DISTANCE',changed?'15.2 km':'18.4 km','Optimized route'],['⌖','PLACES',changed?'4':'5','All available']].map(x=><article key={x[1]}><i>{x[0]}</i><small>{x[1]}</small><b>{x[2]}</b><em>{x[3]}</em></article>)}</div><div className="why">✦ <span><small>WHY THIS PLAN?</small><p>Your itinerary prioritizes beaches, food, and photography while using free attractions to protect your food budget.</p></span></div><div className="matched"><small>PREFERENCES MATCHED</small><p>✓ Beach &nbsp; ✓ Food &nbsp; ✓ Photography</p></div></aside>}
function Dashboard({active,changed,start,event,home}:{active:boolean,changed:boolean,start:()=>void,event:(x:EventType)=>void,home:()=>void}){return <main className="dashboard"><div className="dash-nav"><Logo/><div className="trip-title">⌖ <span><b>Chennai Adventure</b><small>28 Aug · 4 travelers</small></span></div><span className="avatar" onClick={home}>AK</span></div>{active&&<div className="live"><b>● TRIP IN PROGRESS</b><span>Your day is on track ✓</span><div><small>NEXT STOP</small> {changed?'Mylapore Food Walk':'Semmozhi Poonga'} · 16 min away</div><button>NAVIGATE ↗</button></div>}<div className="dash-grid"><Timeline changed={changed}/><Map changed={changed}/><Intel changed={changed}/></div>{!active?<div className="dock ready"><div>✦ <span><b>Your smart itinerary is ready.</b><small>5 places · ₹1,150 remaining · 92% match</small></span></div><Button onClick={start}>Start trip ↗</Button></div>:<div className="dock changes"><div><small>SOMETHING CHANGED?</small><b>We’ll repair the rest.</b></div>{[['☂','Weather changed'],['◷','Running late'],['₹','Budget changed'],['⊘','Place unavailable']].map(x=><button key={x[1]} onClick={()=>event(x[1] as EventType)}><i>{x[0]}</i><span><b>{x[1]}</b><small>Adapt my plan</small></span></button>)}</div>}<button className="ask">✦ &nbsp; Ask TravelMind</button></main>}
function Modal({type,close,adapt}:{type:EventType,close:()=>void,adapt:()=>void}){const [sel,setSel]=useState(type==='Running late'?'2 hours':type==='Weather changed'?'Heavy rain':'');const opts=type==='Running late'?['30 min','1 hour','2 hours','3 hours']:type==='Weather changed'?['Light rain','Heavy rain','Very hot','Weather cleared']:type==='Budget changed'?['₹500','₹1,000','₹1,500','₹2,000']:['Semmozhi Poonga','Mylapore Food Walk','Express Avenue','Marina Beach'];return <div className="shade"><section className="modal"><button className="close" onClick={close}>×</button><div className="modal-icon">{type==='Running late'?'◷':type==='Weather changed'?'☂':type==='Budget changed'?'₹':'⊘'}</div><div className="kicker">ADAPTIVE TRIP RECOVERY</div><h2>{type==='Running late'?'How late are you?':type==='Weather changed'?'What changed?':type==='Budget changed'?"What's your remaining budget?":'Which place is unavailable?'}</h2><p>I’ll preserve your highest-value stops and repair only the affected plan.</p><div className="options">{opts.map(x=><button className={sel===x?'selected':''} onClick={()=>setSel(x)} key={x}>{x}<span>{sel===x?'●':'○'}</span></button>)}</div><aside>⌁ <span><b>Minimum disruption mode</b><small>Completed activities and high-preference places stay protected.</small></span></aside><Button onClick={adapt}>Repair my plan ↻</Button></section></div>}
function Recovery({accept}:{accept:()=>void}){return <main className="recovery"><Top/><section className="rec-hero"><div className="success">✓</div><div><div className="kicker">ADAPTIVE RECOVERY COMPLETE</div><h1>Your trip has been adapted.</h1><p>We changed as little as possible and kept the places you care about most.</p></div><Button onClick={accept}>Use updated plan ↗</Button></section><div className="impact">{[['◷','1h 45m','TIME RECOVERED'],['₹','₹350','BUDGET SAVED'],['⌁','3.2 km','ROUTE REDUCED'],['♡','4 / 5','ACTIVITIES PRESERVED']].map(x=><article key={x[2]}><i>{x[0]}</i><b>{x[1]}</b><small>{x[2]}</small></article>)}</div><section className="comparison"><div className="comp-head"><div><small>BEFORE & AFTER</small><h2>Only what needed to change.</h2></div><p><i className="kept">● Kept</i><i className="moved">● Moved</i><i className="removed">● Removed</i><i className="replaced">● Replaced</i></p></div><div className="plans"><Plan title="ORIGINAL PLAN" data={[['12:30','Mylapore Food Walk','KEPT'],['15:00','Express Avenue','REMOVED'],['17:15','Marina Beach','MOVED']]}/><strong>→</strong><Plan title="UPDATED PLAN" data={[['12:20','Mylapore Food Walk','KEPT'],['15:10','San Thome Basilica','REPLACED'],['17:30','Marina Beach','MOVED']]}/></div></section><section className="decision"><div className="decision-title">✦ <span><small>TRAVELMIND DECISION</small><h2>Why I changed your plan</h2></span></div><div>{[['×','Express Avenue was removed','Your 2-hour delay left insufficient time, and it had the lowest preference match.','removed'],['✓','Marina Beach was protected','It has your highest preference match at 94% and is ideal for sunset photography.','kept'],['↻','San Thome was added','A nearby indoor photography alternative that keeps the route efficient.','replaced']].map(x=><article key={x[1]}><i className={x[3]}>{x[0]}</i><p><b>{x[1]}</b><br/>{x[2]}</p></article>)}</div></section></main>}
function Plan({title,data}:{title:string,data:string[][]}){return <div className="plan"><header><b>{title}</b><small>{data.length} ACTIVITIES</small></header>{data.map(x=><article key={x[1]}><time>{x[0]}</time><span><b>{x[1]}</b><small>High preference activity</small></span><i className={x[2].toLowerCase()}>{x[2]}</i></article>)}</div>}
export default function Page(){const [view,setView]=useState<View>('home');const [event,setEvent]=useState<EventType>(null);const [changed,setChanged]=useState(false);if(view==='home')return <Home go={()=>setView('understand')}/>;if(view==='understand')return <Understand back={()=>setView('home')} next={()=>setView('loading')}/>;if(view==='loading')return <Loading done={()=>setView('trip')}/>;if(view==='recovery')return <Recovery accept={()=>{setChanged(true);setView('active')}}/>;return <><Dashboard active={view==='active'} changed={changed} start={()=>setView('active')} event={setEvent} home={()=>setView('home')}/>{event&&<Modal type={event} close={()=>setEvent(null)} adapt={()=>{setEvent(null);setView('recovery')}}/>}</>}
