import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import tripRoutes from './routes/trip.routes.js';
import placeRoutes from './routes/place.routes.js';
import authRoutes from './routes/auth.routes.js';
import aiRoutes from './routes/ai.routes.js';
import geocodeRoutes from './routes/geocode.routes.js';
import understandingRoutes from './routes/understanding.routes.js';
import weatherRoutes from './routes/weather.routes.js';
import directionRoutes from './routes/direction.routes.js';
import chatRoutes from './routes/chat.routes.js';
import destinationRoutes from './routes/destination.routes.js';
export const app=express();
const allowedOrigins=new Set([process.env.FRONTEND_URL,'http://localhost:3000','http://localhost:5173'].filter(Boolean));
app.use(helmet(),cors({origin:(origin,callback)=>!origin||allowedOrigins.has(origin)?callback(null,true):callback(new Error('Origin not allowed by CORS'))}),express.json({limit:'100kb'}));
app.get('/api/health',(_,res)=>res.json({ok:true,demoMode:process.env.DEMO_MODE!=='false'}));
app.use('/api/trips',tripRoutes);app.use('/api/places',placeRoutes);
app.use('/api/auth',authRoutes);
app.use('/api/ai',aiRoutes);app.use('/api/geocode',geocodeRoutes);
app.use('/api/trip',understandingRoutes);app.use('/api/weather',weatherRoutes);app.use('/api/routes',directionRoutes);app.use('/api/chat',chatRoutes);
app.use('/api/destinations',destinationRoutes);
app.use((err,_,res,next)=>{if(res.headersSent)return next(err);console.error(err);res.status(err.status||500).json({message:err.message||'TravelMind could not complete that request.'})});
